# azure-pipelines.yml  (tillagt efter build-steget)
stages:
# --- Build stage finns redan här ---

# --- Deploy stage ---
- stage: Deploy
  displayName: Deploy to App Service
  dependsOn: Build   # byt om din build-stage heter annat
  jobs:
  - deployment: WebDeploy
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current   # hämtar drop-artefakten
          - task: AzureWebApp@1
            displayName: 'Deploy Blazor zip'
            inputs:
              azureSubscription: 'AzureSPN'
              appType: 'webApp'
              appName: 'ekg-webapp'      # exakt namn i Azure
              package: $(Pipeline.Workspace)/drop/**/*.zip
